version: 2.1

orbs:
  docker: circleci/docker@1.7.0

jobs:
  run-test-build:
    docker:
      - image: cimg/base:stable

    steps:
      - checkout
      - docker/build:
          # The test build validates that the application can and will 
          # build on the production/nightly servers. This doesn't 
          # run any tests or linting, but it does at least provide
          # some insight if we break things too badly.
          image: core-test-build 


workflows:
  test-build-workflow:
    jobs:
      - run-test-build
